// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type {
  BaseTranslation as BaseTranslationType,
  LocalizedString,
} from "typesafe-i18n";

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = "en";

export type Locales = "en" | "ja";

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  /**
   * H​e​l​l​o​ ​W​o​r​l​d
   */
  hello: string;
  /**
   * M​a​s​a​k​i​ ​Y​o​s​h​i​i​w​a
   */
  name: string;
  /**
   * A​b​o​u​t
   */
  about: string;
  /**
   * M​y​ ​P​r​o​j​e​c​t​s
   */
  myProjects: string;
  /**
   * P​r​o​j​e​c​t​s​ ​I​'​m​ ​I​n​t​e​r​e​s​t​e​d​ ​I​n
   */
  projects: string;
  /**
   * V​i​e​w​ ​a​l​l​ ​p​r​o​j​e​c​t​s​ ​i​n​ ​G​i​t​H​u​b​.
   */
  viewAllProjects: string;
  /**
   * R​e​c​e​n​t​ ​B​l​o​g​ ​P​o​s​t​s
   */
  recentBlogPosts: string;
};

export type TranslationFunctions = {
  /**
   * Hello World
   */
  hello: () => LocalizedString;
  /**
   * Masaki Yoshiiwa
   */
  name: () => LocalizedString;
  /**
   * About
   */
  about: () => LocalizedString;
  /**
   * My Projects
   */
  myProjects: () => LocalizedString;
  /**
   * Projects I'm Interested In
   */
  projects: () => LocalizedString;
  /**
   * View all projects in GitHub.
   */
  viewAllProjects: () => LocalizedString;
  /**
   * Recent Blog Posts
   */
  recentBlogPosts: () => LocalizedString;
};

export type Formatters = {};
